development:
  adapter: postgresql
  database: eventoscte
  host: localhost

test:
  adapter: postgresql
  database: eventoscte2
  host: localhost

production:
  adapter: postgresql
  database: eventoscte
  host: localhost