development:
  adapter: postgresql
  database: eventoscte
  host: localhost

test:
  adapter: postgresql
  database: eventoscte_teste
  host: localhost

production:
  adapter: postgresql
  database: eventoscte
  host: localhost